package org.cocktail.edtweb.server.components;
// Generated by the WOLips Core at Fri Aug 27 09:15:45 CEST 2004

import org.cocktail.edtweb.server.Application;

import com.webobjects.appserver.WOContext;
import com.webobjects.eocontrol.EOGenericRecord;
import com.webobjects.eocontrol.EOQualifier;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;
import com.webobjects.foundation.NSTimestamp;

import fr.univlr.cri.webapp.LRUserInfo;
import fr.univlr.cri.webapp.LRUserInfoDB;

public class EDTIndividuPublic extends EDTIndividu {
	private static final long serialVersionUID = 9104804025808057218L;
	public static final String LOGIN_EXTERNE = "loginExterne";
	public LRUserInfo localUser;

	public EDTIndividuPublic(final WOContext context) {
		super(context);
	}

	public boolean showPublicEtPrive() {
		return false;
	}

	public void initEDTIndividu() {
		listeResa = new NSMutableArray();
		responder = new Responder();
		dateDebut = new NSTimestamp();
		heureDebut = (new Integer(((Application) application()).heureDebutParDefaut())).toString();
		heureFin = (new Integer(((Application) application()).heureFinParDefaut())).toString();
		final NSMutableArray liste = new NSMutableArray();
		localUser = new LRUserInfoDB(criApp.dataBus());
		localUser.compteForLogin((String) session().objectForKey(LOGIN_EXTERNE), null, true);
		if (localUser.errorCode() == LRUserInfo.ERROR_NONE) {
			liste.addObject(localUser.noIndividu());
			session().setObjectForKey(liste, AffichePlanning.LISTE_OBJET);
			session().setObjectForKey(responder, AffichePlanning.RESPONDER);
			final EOGenericRecord agenda = (EOGenericRecord) criApp.dataBus().fetchObject(localEContext(), "IndividuAgenda",
					EOQualifier.qualifierWithQualifierFormat("noIndividu = %@", new NSArray(localUser.noIndividu())));
			if ("O".equals(agenda.valueForKey("showAgendaPublic"))) {
				setShowPlanning(true);
			}
			else {
				setShowPlanning(false);
			}
		}
		else {
			setShowPlanning(false);
		}

	}

	public String titrePlanning() {
		return "Planning de disponibilit&eacute; de " + localUser.nomEtPrenom();
	}

}