package org.cocktail.edtweb.server.components;
// Generated by the WOLips Core at Tue Jul 27 09:21:19 CEST 2004

import org.cocktail.edtweb.server.metier.Salles;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.eocontrol.EOAndQualifier;
import com.webobjects.eocontrol.EOEditingContext;
import com.webobjects.eocontrol.EOOrQualifier;
import com.webobjects.eocontrol.EOQualifier;
import com.webobjects.eocontrol.EOSortOrdering;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;
import com.webobjects.foundation.NSTimestamp;

import fr.univlr.cri.webapp.CRIWebComponent;
import fr.univlr.cri.webext.CRIWebMenu;
import fr.univlr.cri.webext.CRIWebMenuItemSet;
import fr.univlr.cri.webext.CRIWebMenuListener;

public class EDTSalleMenu extends CRIWebComponent {
	private static final long serialVersionUID = -2641684297912395541L;
	public static final String SALLE_SELECTED = "salleSelected";
	public static final String SHOW_PLANNING = "showLePlanning";
	// pour le criwebmenu
	public MenuListener menuListener;
	public CRIWebMenu webMenu;
	public CRIWebMenuItemSet menuItem;
	protected int noItemSelected;

	protected NSArray listSalle;
	protected NSArray listImplantationGeos;

	public EDTSalleMenu(final WOContext context) {
		super(context);
		webMenu = new CRIWebMenu(context);
		// on rempli le menu.....

		// init listener
		menuListener = new MenuListener();
		menuListener.initMenu(webMenu);

		// init item du menu
		menuItem = new CRIWebMenuItemSet();
		menuItem = initMenuItems();
	}

	protected EOEditingContext localEContext() {
		return session().defaultEditingContext();
	}

	// Definit une classe de receveur d'evenements de menu.
	public class MenuListener implements CRIWebMenuListener {
		public void initMenu(final CRIWebMenu menu) {
			// En general, on ne fait rien dans cette methode
		}

		// La methode appelee chaque fois qu'un evenement est genere.
		public WOComponent selectMenu(final CRIWebMenu menu, final int menuId) {
			if (menuId >= listSalle.count()) {
				return criSession().logout();
			}
			final Salles objet = (Salles) listSalle.objectAtIndex(menuId);
			session().setObjectForKey(objet, SALLE_SELECTED);
			session().setObjectForKey(Boolean.TRUE, SHOW_PLANNING);
			session().setObjectForKey(new Boolean(true), "refresh");
			return null;
		}

	}

	// Construit et renvoie une collection des elements
	// du menu. Pourrait etre appelee une fois.
	protected CRIWebMenuItemSet initMenuItems() {
		final CRIWebMenuItemSet menuItemSet = new CRIWebMenuItemSet();
		// on recupÃ¨re les types d'objet qui ne doivent pas Ãªtre affichÃ©s
		final NSMutableArray args = new NSMutableArray();
		args.addObject(EOQualifier.qualifierWithQualifierFormat("salReservable = %@", new NSArray("O")));
		args.addObject(EOQualifier.qualifierWithQualifierFormat("batDebVal <= %@", new NSArray(new NSTimestamp())));
		final NSMutableArray args2 = new NSMutableArray();
		args2.addObject(EOQualifier.qualifierWithQualifierFormat("batFinVal >=%@", new NSArray(new NSTimestamp())));
		args2.addObject(EOQualifier.qualifierWithQualifierFormat("batFinVal = nil", null));
		args.addObject(new EOOrQualifier(args2));

		final NSMutableArray sort = new NSMutableArray();
		sort.addObject(EOSortOrdering.sortOrderingWithKey("batNom", EOSortOrdering.CompareAscending));
		sort.addObject(EOSortOrdering.sortOrderingWithKey("salEtage", EOSortOrdering.CompareAscending));
		sort.addObject(EOSortOrdering.sortOrderingWithKey("salPorte", EOSortOrdering.CompareAscending));
		listSalle = criApp.dataBus().fetchArray(localEContext(), "Salles", new EOAndQualifier(args), sort);
		String typeEnCours = null;
		int niveau1 = 0;
		int niveau2 = 0;
		String etage = "";
		// LRLog.trace("listObjet = "+listObjet);
		for (int i = 0; i < listSalle.count(); i++) {
			final Salles objet = (Salles) listSalle.objectAtIndex(i);
			// LRLog.trace("objet = "+objet);
			if (typeEnCours == null || !typeEnCours.equals(objet.valueForKey("batNom"))) {
				// Les entrees du premier niveau
				menuItemSet.addMenuItem(niveau1, (String) objet.valueForKey("batNom"), (String) objet.valueForKey("batNom"), "_self");
				niveau1++;
				typeEnCours = (String) objet.valueForKey("batNom");
			}
			if ("0".equals(objet.valueForKey("salEtage"))) {
				etage = "Rdc";
			}
			else {
				if ("1".equals(objet.valueForKey("salEtage"))) {
					etage = "1er";
				}
				else {
					etage = (String) objet.valueForKey("salEtage") + "ème";
				}
			}

			menuItemSet.addMenuSubItem(niveau1 - 1, niveau2, etage + ":   " + (String) objet.valueForKey("salPorte"), "Etage: "
					+ (String) objet.valueForKey("salEtage") + " Porte: " + objet.valueForKey("salPorte"), "_self");
			niveau2++;
		}
		// String decoDebut = "<font color=\"#FEDB70\" class=\"\" font-family=\"Arial, Verdana, Microsoft Sans Serif, MS Sans Serif,
		// Helvetica, sans-serif\" font-size=\"11px\" font-weight=\" bold\"><B>";
		// String decoFin = "</B></font>";
		// menuItemSet.addMenuItem(niveau2, decoDebut + "Quitter" + decoFin, "Quitter l'application", "_self");

		return menuItemSet;
	}

}