package org.cocktail.edtweb.server.components;
// Generated by the WOLips Core at Mon Jun 07 13:52:00 CEST 2004

import com.webobjects.appserver.WOContext;

import fr.univlr.cri.webapp.CRIWebPage;

public class services extends CRIWebPage {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5805992077310599192L;

	public services(final WOContext context) {
		super(context);
	}

}